### ISSUE TITLE
write get_causative_variants_from_scout

### ISSUE THREAD

**Issue by henrikstranneheim** [adrosenbaum/mutacc#12]
Via Scout CLI:
```
scout view cases --causatives
```
Return: JSON text -> dump as flat file and load as JSON object.

**Comment by adrosenbaum** [comment]
Why should I use the scout CLI output instead of querying the scout mongoDB directly? The JSON output from the scout CLI is not very easy to parse with e.g. the json module in python, seeing that it contains mongoDB types that are not parsed automatically (ObjectId, datetime, ...). If I am to parse the scout CLI output it seems I need to do a lot of modification on the output string for it to be considered valid JSON by python.

**Comment by moonso** [comment]
There are two options in the latest version of scout. Either 

1. `scout export cases --causatives`, this will return all cases that have causative variants
1. `scout export variants` this will return all causative variants

Both of them have a flag `--json` that will print a list of json objects to the console.
`scout export variants --document-id <_id>` can be used to retrieve a single variant.

Good luck!
